/usr/bin/time -o bcftools_convert_r1_s10.time -f "%E %M" bcftools convert --samples-file ^r1_s10.nsv -o pruned_r1_s10.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s10.time -f "%E %M" bcftools convert --samples-file ^r2_s10.nsv -o pruned_r2_s10.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s10.time -f "%E %M" bcftools convert --samples-file ^r3_s10.nsv -o pruned_r3_s10.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s50.time -f "%E %M" bcftools convert --samples-file ^r1_s50.nsv -o pruned_r1_s50.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s50.time -f "%E %M" bcftools convert --samples-file ^r2_s50.nsv -o pruned_r2_s50.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s50.time -f "%E %M" bcftools convert --samples-file ^r3_s50.nsv -o pruned_r3_s50.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s100.time -f "%E %M" bcftools convert --samples-file ^r1_s100.nsv -o pruned_r1_s100.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s100.time -f "%E %M" bcftools convert --samples-file ^r2_s100.nsv -o pruned_r2_s100.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s100.time -f "%E %M" bcftools convert --samples-file ^r3_s100.nsv -o pruned_r3_s100.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s500.time -f "%E %M" bcftools convert --samples-file ^r1_s500.nsv -o pruned_r1_s500.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s500.time -f "%E %M" bcftools convert --samples-file ^r2_s500.nsv -o pruned_r2_s500.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s500.time -f "%E %M" bcftools convert --samples-file ^r3_s500.nsv -o pruned_r3_s500.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s1000.time -f "%E %M" bcftools convert --samples-file ^r1_s1000.nsv -o pruned_r1_s1000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s1000.time -f "%E %M" bcftools convert --samples-file ^r2_s1000.nsv -o pruned_r2_s1000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s1000.time -f "%E %M" bcftools convert --samples-file ^r3_s1000.nsv -o pruned_r3_s1000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s5000.time -f "%E %M" bcftools convert --samples-file ^r1_s5000.nsv -o pruned_r1_s5000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s5000.time -f "%E %M" bcftools convert --samples-file ^r2_s5000.nsv -o pruned_r2_s5000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s5000.time -f "%E %M" bcftools convert --samples-file ^r3_s5000.nsv -o pruned_r3_s5000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s10000.time -f "%E %M" bcftools convert --samples-file ^r1_s10000.nsv -o pruned_r1_s10000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s10000.time -f "%E %M" bcftools convert --samples-file ^r2_s10000.nsv -o pruned_r2_s10000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s10000.time -f "%E %M" bcftools convert --samples-file ^r3_s10000.nsv -o pruned_r3_s10000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s50000.time -f "%E %M" bcftools convert --samples-file ^r1_s50000.nsv -o pruned_r1_s50000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s50000.time -f "%E %M" bcftools convert --samples-file ^r2_s50000.nsv -o pruned_r2_s50000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s50000.time -f "%E %M" bcftools convert --samples-file ^r3_s50000.nsv -o pruned_r3_s50000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s100000.time -f "%E %M" bcftools convert --samples-file ^r1_s100000.nsv -o pruned_r1_s100000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s100000.time -f "%E %M" bcftools convert --samples-file ^r2_s100000.nsv -o pruned_r2_s100000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s100000.time -f "%E %M" bcftools convert --samples-file ^r3_s100000.nsv -o pruned_r3_s100000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r1_s250000.time -f "%E %M" bcftools convert --samples-file ^r1_s250000.nsv -o pruned_r1_s250000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r2_s250000.time -f "%E %M" bcftools convert --samples-file ^r2_s250000.nsv -o pruned_r2_s250000.vcf.gz -O z new.fixed.vcf.gz
/usr/bin/time -o bcftools_convert_r3_s250000.time -f "%E %M" bcftools convert --samples-file ^r3_s250000.nsv -o pruned_r3_s250000.vcf.gz -O z new.fixed.vcf.gz

